//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.MainMultilangConst", typeof(MainMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string _BrowserPathDialogFilterFileType {
            get {
                return ResourceManager.GetString("_BrowserPathDialogFilterFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The config cannot be recognized. Check if the config contain syntax errors 的本地化字符串。
        /// </summary>
        public static string _ConfErrorMsg {
            get {
                return ResourceManager.GetString("_ConfErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I know you would do it, but nothing will actually happen. Whee. 的本地化字符串。
        /// </summary>
        public static string _GameClickOnceMsg {
            get {
                return ResourceManager.GetString("_GameClickOnceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ugh, what are you doing. Please stop, I don&apos;t want to hurt anyone. Stop please, this is your last chance. Ugh, I can&apos;t control it anymore. 的本地化字符串。
        /// </summary>
        public static string _GameClickThreeMsg {
            get {
                return ResourceManager.GetString("_GameClickThreeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No no no, don&apos;t click me. Sorry, I shouldn&apos;t have lied to you, I am a cursed button, and continuing to click me will bring disaster to the entire Sheas Cealer. Please believe me, this is not a game, and there are no new features here. Listen to me and use the normal functions, okay? 的本地化字符串。
        /// </summary>
        public static string _GameClickTwiceMsg {
            get {
                return ResourceManager.GetString("_GameClickTwiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You defeated the evil button and saved Sheas Cealer, you are hero 的本地化字符串。
        /// </summary>
        public static string _GameEndingMsg {
            get {
                return ResourceManager.GetString("_GameEndingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Remaining HP. 的本地化字符串。
        /// </summary>
        public static string _GameGradeMsg {
            get {
                return ResourceManager.GetString("_GameGradeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s dead, and you&apos;re the hero of Sheas Cealer 的本地化字符串。
        /// </summary>
        public static string _GameReviewEndingMsg {
            get {
                return ResourceManager.GetString("_GameReviewEndingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No, please kill me, I...can&apos;t control myself... 的本地化字符串。
        /// </summary>
        public static string _GameStartMsg {
            get {
                return ResourceManager.GetString("_GameStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The args cannot be recognized. Check if the hosts contain syntax errors 的本地化字符串。
        /// </summary>
        public static string _HostErrorMsg {
            get {
                return ResourceManager.GetString("_HostErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All processes of the selected browser will be closed before launching. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _KillBrowserProcessPrompt {
            get {
                return ResourceManager.GetString("_KillBrowserProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please remember to come back and stop the proxy manually after use. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _LaunchProxyPrompt {
            get {
                return ResourceManager.GetString("_LaunchProxyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an update available. Do you want to update upstream host? If No it will only open the upstream host page for you 的本地化字符串。
        /// </summary>
        public static string _OverrideUpstreamHostPrompt {
            get {
                return ResourceManager.GetString("_OverrideUpstreamHostPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update successfully 的本地化字符串。
        /// </summary>
        public static string _UpdateUpstreamHostSuccessMsg {
            get {
                return ResourceManager.GetString("_UpdateUpstreamHostSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream host has been updated to the latest 的本地化字符串。
        /// </summary>
        public static string _UpstreamHostUtdMsg {
            get {
                return ResourceManager.GetString("_UpstreamHostUtdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open an about window 的本地化字符串。
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Path 的本地化字符串。
        /// </summary>
        public static string BrowserPathSettingsModeName {
            get {
                return ResourceManager.GetString("BrowserPathSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Hosts Conf 的本地化字符串。
        /// </summary>
        public static string EditHostsConfButtonContent {
            get {
                return ResourceManager.GetString("EditHostsConfButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit hosts conf 的本地化字符串。
        /// </summary>
        public static string EditHostsConfButtonToolTip {
            get {
                return ResourceManager.GetString("EditHostsConfButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Local Host 的本地化字符串。
        /// </summary>
        public static string EditLocalHostButtonContent {
            get {
                return ResourceManager.GetString("EditLocalHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit local host 的本地化字符串。
        /// </summary>
        public static string EditLocalHostButtonToolTip {
            get {
                return ResourceManager.GetString("EditLocalHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Mihomo Conf 的本地化字符串。
        /// </summary>
        public static string EditMihomoConfButtonContent {
            get {
                return ResourceManager.GetString("EditMihomoConfButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit mihomo conf 的本地化字符串。
        /// </summary>
        public static string EditMihomoConfButtonToolTip {
            get {
                return ResourceManager.GetString("EditMihomoConfButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Nginx Conf 的本地化字符串。
        /// </summary>
        public static string EditNginxConfButtonContent {
            get {
                return ResourceManager.GetString("EditNginxConfButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit nginx conf 的本地化字符串。
        /// </summary>
        public static string EditNginxConfButtonToolTip {
            get {
                return ResourceManager.GetString("EditNginxConfButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit UPSTR. Host 的本地化字符串。
        /// </summary>
        public static string EditUpstreamHostButtonContent {
            get {
                return ResourceManager.GetString("EditUpstreamHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit upstream host 的本地化字符串。
        /// </summary>
        public static string EditUpstreamHostButtonToolTip {
            get {
                return ResourceManager.GetString("EditUpstreamHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Args 的本地化字符串。
        /// </summary>
        public static string ExtraArgsSettingsModeName {
            get {
                return ResourceManager.GetString("ExtraArgsSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Purging INIT. 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsInitingContent {
            get {
                return ResourceManager.GetString("MihomoButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Global Purging 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsRunningContent {
            get {
                return ResourceManager.GetString("MihomoButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("MihomoButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Global Purging 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("MihomoButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("MihomoButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLB. Cealing INIT. 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsInitingContent {
            get {
                return ResourceManager.GetString("NginxButtonIsInitingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop GLB. Cealing 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningContent {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start GLB. Cealing 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Now 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsFlashingContent {
            get {
                return ResourceManager.GetString("NoClickButtonIsFlashingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the button now 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsFlashingToolTip {
            get {
                return ResourceManager.GetString("NoClickButtonIsFlashingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Clicking 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("NoClickButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donot click the button 的本地化字符串。
        /// </summary>
        public static string NoClickButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("NoClickButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in a Chromium-based browser path 的本地化字符串。
        /// </summary>
        public static string SettingsBoxBrowserPathToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxBrowserPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in extra Chromium startup args 的本地化字符串。
        /// </summary>
        public static string SettingsBoxExtraArgsToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxExtraArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in an upstream host URL 的本地化字符串。
        /// </summary>
        public static string SettingsBoxUpstreamUrlToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxUpstreamUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Path 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonBrowserPathContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonBrowserPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Args 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonExtraArgsContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonExtraArgsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to process settings 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset URL 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonUpstreamUrlContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonUpstreamUrlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch settings 的本地化字符串。
        /// </summary>
        public static string SettingsModeButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsModeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Cealing 的本地化字符串。
        /// </summary>
        public static string StartButtonContent {
            get {
                return ResourceManager.GetString("StartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch an injected browser 的本地化字符串。
        /// </summary>
        public static string StartButtonToolTip {
            get {
                return ResourceManager.GetString("StartButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonDarkThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonDarkThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonInheritThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonInheritThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonLightThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonLightThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch themes 的本地化字符串。
        /// </summary>
        public static string ThemesButtonToolTip {
            get {
                return ResourceManager.GetString("ThemesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Upstream Host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonContent {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to update upstream host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream URL 的本地化字符串。
        /// </summary>
        public static string UpstreamUrlSettingsModeName {
            get {
                return ResourceManager.GetString("UpstreamUrlSettingsModeName", resourceCulture);
            }
        }
    }
}
