//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.MainMultilangConst", typeof(MainMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string _BrowserPathDialogFilterFileType {
            get {
                return ResourceManager.GetString("_BrowserPathDialogFilterFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The config cannot be recognized, check if the config contain syntax errors 的本地化字符串。
        /// </summary>
        public static string _ConfigErrorHint {
            get {
                return ResourceManager.GetString("_ConfigErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The args cannot be recognized, check if the hosts contain syntax errors 的本地化字符串。
        /// </summary>
        public static string _HostErrorHint {
            get {
                return ResourceManager.GetString("_HostErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All processes of the selected browser will be closed before launching, do you want to continue? 的本地化字符串。
        /// </summary>
        public static string _KillBrowserProcessPrompt {
            get {
                return ResourceManager.GetString("_KillBrowserProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an update available. Do you want to update upstream host? If No it will only open the upstream host page for you 的本地化字符串。
        /// </summary>
        public static string _OverrideUpstreamHostPrompt {
            get {
                return ResourceManager.GetString("_OverrideUpstreamHostPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update successfully 的本地化字符串。
        /// </summary>
        public static string _UpdateUpstreamHostSuccessHint {
            get {
                return ResourceManager.GetString("_UpdateUpstreamHostSuccessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream host has been updated to the latest 的本地化字符串。
        /// </summary>
        public static string _UpstreamHostUtdHint {
            get {
                return ResourceManager.GetString("_UpstreamHostUtdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open an about window 的本地化字符串。
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Path 的本地化字符串。
        /// </summary>
        public static string BrowserPathSettingsModeName {
            get {
                return ResourceManager.GetString("BrowserPathSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Local Host 的本地化字符串。
        /// </summary>
        public static string EditLocalHostButtonContent {
            get {
                return ResourceManager.GetString("EditLocalHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit local host 的本地化字符串。
        /// </summary>
        public static string EditLocalHostButtonToolTip {
            get {
                return ResourceManager.GetString("EditLocalHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Upstream Host 的本地化字符串。
        /// </summary>
        public static string EditUpstreamHostButtonContent {
            get {
                return ResourceManager.GetString("EditUpstreamHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit upstream host 的本地化字符串。
        /// </summary>
        public static string EditUpstreamHostButtonToolTip {
            get {
                return ResourceManager.GetString("EditUpstreamHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Args 的本地化字符串。
        /// </summary>
        public static string ExtraArgsSettingsModeName {
            get {
                return ResourceManager.GetString("ExtraArgsSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsRunningContent {
            get {
                return ResourceManager.GetString("MihomoButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("MihomoButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("MihomoButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Mihomo 的本地化字符串。
        /// </summary>
        public static string MihomoButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("MihomoButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningContent {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop the local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsRunningToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedContent {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch a local Nginx 的本地化字符串。
        /// </summary>
        public static string NginxButtonIsStoppedToolTip {
            get {
                return ResourceManager.GetString("NginxButtonIsStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in a Chromium-based browser path 的本地化字符串。
        /// </summary>
        public static string SettingsBoxBrowserPathToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxBrowserPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in extra Chromium startup args 的本地化字符串。
        /// </summary>
        public static string SettingsBoxExtraArgsToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxExtraArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in an upstream host URL 的本地化字符串。
        /// </summary>
        public static string SettingsBoxUpstreamUrlToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxUpstreamUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Path 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonBrowserPathContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonBrowserPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Args 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonExtraArgsContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonExtraArgsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to process settings 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset URL 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonUpstreamUrlContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonUpstreamUrlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch settings 的本地化字符串。
        /// </summary>
        public static string SettingsModeButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsModeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Cealing 的本地化字符串。
        /// </summary>
        public static string StartButtonContent {
            get {
                return ResourceManager.GetString("StartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch an injected browser 的本地化字符串。
        /// </summary>
        public static string StartButtonToolTip {
            get {
                return ResourceManager.GetString("StartButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonDarkThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonDarkThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonInheritThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonInheritThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonLightThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonLightThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch themes 的本地化字符串。
        /// </summary>
        public static string ThemesButtonToolTip {
            get {
                return ResourceManager.GetString("ThemesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Upstream Host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonContent {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to update upstream host 的本地化字符串。
        /// </summary>
        public static string UpdateUpstreamHostButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateUpstreamHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream URL 的本地化字符串。
        /// </summary>
        public static string UpstreamUrlSettingsModeName {
            get {
                return ResourceManager.GetString("UpstreamUrlSettingsModeName", resourceCulture);
            }
        }
    }
}
