//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer.Consts.MainMultilangConst", typeof(MainMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open an about window 的本地化字符串。
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Path 的本地化字符串。
        /// </summary>
        public static string BrowserPathSettingsModeName {
            get {
                return ResourceManager.GetString("BrowserPathSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Host 的本地化字符串。
        /// </summary>
        public static string EditHostButtonContent {
            get {
                return ResourceManager.GetString("EditHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to edit host 的本地化字符串。
        /// </summary>
        public static string EditHostButtonToolTip {
            get {
                return ResourceManager.GetString("EditHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Args 的本地化字符串。
        /// </summary>
        public static string ExtraArgsSettingsModeName {
            get {
                return ResourceManager.GetString("ExtraArgsSettingsModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in a Chromium-based browser path 的本地化字符串。
        /// </summary>
        public static string SettingsBoxBrowserPathToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxBrowserPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in extra Chromium startup args 的本地化字符串。
        /// </summary>
        public static string SettingsBoxExtraArgsToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxExtraArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in an upstream host URL 的本地化字符串。
        /// </summary>
        public static string SettingsBoxUpstreamUrlToolTip {
            get {
                return ResourceManager.GetString("SettingsBoxUpstreamUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Path 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonBrowserPathContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonBrowserPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Args 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonExtraArgsContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonExtraArgsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to process settings 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset URL 的本地化字符串。
        /// </summary>
        public static string SettingsFunctionButtonUpstreamUrlContent {
            get {
                return ResourceManager.GetString("SettingsFunctionButtonUpstreamUrlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch settings 的本地化字符串。
        /// </summary>
        public static string SettingsModeButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsModeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Cealing 的本地化字符串。
        /// </summary>
        public static string StartButtonContent {
            get {
                return ResourceManager.GetString("StartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to launch an injected browser 的本地化字符串。
        /// </summary>
        public static string StartButtonToolTip {
            get {
                return ResourceManager.GetString("StartButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonDarkThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonDarkThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonInheritThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonInheritThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        public static string ThemesButtonLightThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonLightThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch themes 的本地化字符串。
        /// </summary>
        public static string ThemesButtonToolTip {
            get {
                return ResourceManager.GetString("ThemesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Host 的本地化字符串。
        /// </summary>
        public static string UpdateHostButtonContent {
            get {
                return ResourceManager.GetString("UpdateHostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to update host 的本地化字符串。
        /// </summary>
        public static string UpdateHostButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateHostButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upstream URL 的本地化字符串。
        /// </summary>
        public static string UpstreamUrlSettingsModeName {
            get {
                return ResourceManager.GetString("UpstreamUrlSettingsModeName", resourceCulture);
            }
        }
    }
}
