//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Nix.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Nix.Consts.SettingsMultilangConst", typeof(SettingsMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Switch successfuly, restart to refresh the windows 的本地化字符串。
        /// </summary>
        public static string _ChangeLangSuccessMsg {
            get {
                return ResourceManager.GetString("_ChangeLangSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Color (Fully Random) 的本地化字符串。
        /// </summary>
        public static string ColorsButtonContent {
            get {
                return ResourceManager.GetString("ColorsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch colors 的本地化字符串。
        /// </summary>
        public static string ColorsButtonToolTip {
            get {
                return ResourceManager.GetString("ColorsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Lang (中文 → En) 的本地化字符串。
        /// </summary>
        public static string LangsButtonChineseLangContent {
            get {
                return ResourceManager.GetString("LangsButtonChineseLangContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Lang (En → Auto) 的本地化字符串。
        /// </summary>
        public static string LangsButtonEnglishLangContent {
            get {
                return ResourceManager.GetString("LangsButtonEnglishLangContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Lang (Auto → 中文) 的本地化字符串。
        /// </summary>
        public static string LangsButtonInheritLangContent {
            get {
                return ResourceManager.GetString("LangsButtonInheritLangContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch langs 的本地化字符串。
        /// </summary>
        public static string LangsButtonToolTip {
            get {
                return ResourceManager.GetString("LangsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Theme (Dark → Light) 的本地化字符串。
        /// </summary>
        public static string ThemesButtonDarkThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonDarkThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Theme (Auto → Dark) 的本地化字符串。
        /// </summary>
        public static string ThemesButtonInheritThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonInheritThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Theme (Light → Auto) 的本地化字符串。
        /// </summary>
        public static string ThemesButtonLightThemeContent {
            get {
                return ResourceManager.GetString("ThemesButtonLightThemeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch themes 的本地化字符串。
        /// </summary>
        public static string ThemesButtonToolTip {
            get {
                return ResourceManager.GetString("ThemesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Weight (Bold → Light) 的本地化字符串。
        /// </summary>
        public static string WeightsButtonBoldWeightContent {
            get {
                return ResourceManager.GetString("WeightsButtonBoldWeightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Weight (Light → Regular) 的本地化字符串。
        /// </summary>
        public static string WeightsButtonLightWeightContent {
            get {
                return ResourceManager.GetString("WeightsButtonLightWeightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWT. Weight (RGL. → Bold) 的本地化字符串。
        /// </summary>
        public static string WeightsButtonRegularWeightContent {
            get {
                return ResourceManager.GetString("WeightsButtonRegularWeightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to switch font weights 的本地化字符串。
        /// </summary>
        public static string WeightsButtonToolTip {
            get {
                return ResourceManager.GetString("WeightsButtonToolTip", resourceCulture);
            }
        }
    }
}
